import SelorgApi from '../api';

/**
 * Auth + account endpoints — selorg-service `/api/v1/customer/auth` + `/user`.
 *
 * Login is OTP-only (SMS / WhatsApp / email). The flow is:
 *   1. sendOtp({ phoneNumber })            -> { sessionId, channel, resendCooldownSeconds }
 *   2. verifyOtp({ sessionId, otp })       -> { accessToken, isNewUser, user, ... }
 *
 * `SelorgApi` unwraps the `{ success, message, data }` envelope on success and
 * rejects with `{ status, message?, body? }` on failure.
 */

export type OtpChannel = 'sms' | 'whatsapp' | 'email';

export interface SendOtpResult {
  sessionId: string;
  channel: string;
  resendCooldownSeconds: number;
  devNote?: string;
}

export interface AuthUser {
  _id: string;
  phoneNumber?: string;
  email: string | null;
  name: string;
  phoneVerified: boolean;
  avatarUrl?: string;
}

export interface VerifyOtpResult {
  accessToken: string;
  isNewUser: boolean;
  user: AuthUser;
  autoGeneratedPassword?: string;
}

const unwrap = <T,>(res: any): T => (res && 'data' in res ? res.data : res) as T;

export const authApi = {
  /**
   * Send an OTP. Provide `phoneNumber` (10 digits) or `email`.
   * `intent: 'login'` rejects unknown users (`USER_NOT_FOUND`); `'signup'` creates on verify.
   */
  sendOtp: (params: {
    phoneNumber?: string;
    email?: string;
    preferredChannel?: OtpChannel;
    intent?: 'login' | 'signup';
  }): Promise<SendOtpResult> =>
    SelorgApi.post('/auth/send-otp', { data: params }).then(unwrap<SendOtpResult>),

  /** Verify the OTP for a session and receive an access token. */
  verifyOtp: (params: { sessionId: string; otp: string }): Promise<VerifyOtpResult> =>
    SelorgApi.post('/auth/verify-otp', { data: params }).then(unwrap<VerifyOtpResult>),

  /** Re-send the OTP for an existing session (respects the resend cooldown). */
  resendOtp: (params: { sessionId: string }): Promise<{ channel: string; resendCooldownSeconds: number }> =>
    SelorgApi.post('/auth/resend-otp', { data: params }).then(
      unwrap<{ channel: string; resendCooldownSeconds: number }>,
    ),

  logout: (params: { refreshToken?: string } = {}) =>
    SelorgApi.post('/auth/logout', { data: params }),

  // ---- Authenticated account endpoints (`/user`) ----

  getProfile: (): Promise<any> => SelorgApi.get('/user/profile').then(unwrap),

  updateProfile: (data: {
    name?: string;
    email?: string;
    phoneNumber?: string;
    avatarUrl?: string;
  }): Promise<any> => SelorgApi.update('/user/profile', { data }).then(unwrap),
};
