import React from 'react';
import {
  House,
  Grid2x2,
  LayoutGrid,
  ReceiptText,
  ShoppingBasket,
  ShoppingCart,
  EllipsisVertical,
  Mail,
  ArrowUpDown,
  SlidersHorizontal,
  Share2,
  Minus,
  User,
  MapPin,
  Search,
  Package,
  Wallet,
  RotateCcw,
  Settings,
  FileText,
  MessageCircle,
  Tag,
  Zap,
  Truck,
  Phone,
  CreditCard,
  Banknote,
  Landmark,
  Camera,
  ImagePlus,
  Plus,
  Gift,
  Heart,
  Star,
  Building2,
  Send,
  Leaf,
  Check,
  Play,
  Link2,
  ArrowUpRight,
  ArrowRight,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  ChevronUp,
  X,
  Lock,
  WifiOff,
  Clock,
  IndianRupee,
  CircleQuestionMark,
  Apple,
  Shield,
  Eye,
  EyeOff,
  Bell,
  LogOut,
  Trash2,
  PenLine,
  Copy,
  Download,
  ListFilter,
  Percent,
  BadgeCheck,
  Sparkles,
  Ticket,
  ThumbsUp,
  MapPinned,
  Navigation2,
  RefreshCw,
  CircleAlert,
  CircleCheck,
  Info,
  type LucideIcon,
  type LucideProps,
} from 'lucide-react-native';

const ICONS: Record<string, LucideIcon> = {
  home: House,
  grid: Grid2x2,
  categories: LayoutGrid,
  receipt: ReceiptText,
  cart: ShoppingBasket,
  shoppingCart: ShoppingCart,
  moreVert: EllipsisVertical,
  mail: Mail,
  sort: ArrowUpDown,
  sort2: SlidersHorizontal,
  share: Share2,
  minus: Minus,
  user: User,
  pin: MapPin,
  search: Search,
  box: Package,
  wallet: Wallet,
  refund: RotateCcw,
  settings: Settings,
  file: FileText,
  chat: MessageCircle,
  tag: Tag,
  zap: Zap,
  truck: Truck,
  phone: Phone,
  card: CreditCard,
  cash: Banknote,
  bank: Landmark,
  camera: Camera,
  imagePlus: ImagePlus,
  plus: Plus,
  gift: Gift,
  heart: Heart,
  star: Star,
  building: Building2,
  send: Send,
  leaf: Leaf,
  check: Check,
  play: Play,
  link: Link2,
  arrowUpRight: ArrowUpRight,
  arrowRight: ArrowRight,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  chevronUp: ChevronUp,
  x: X,
  lock: Lock,
  wifiOff: WifiOff,
  clock: Clock,
  rupee: IndianRupee,
  help: CircleQuestionMark,
  apple: Apple,
  shield: Shield,
  eye: Eye,
  eyeOff: EyeOff,
  bell: Bell,
  logout: LogOut,
  trash: Trash2,
  edit: PenLine,
  copy: Copy,
  download: Download,
  filter: ListFilter,
  percent: Percent,
  badgeCheck: BadgeCheck,
  sparkles: Sparkles,
  ticket: Ticket,
  thumbsUp: ThumbsUp,
  mapPinned: MapPinned,
  navigation: Navigation2,
  refresh: RefreshCw,
  alert: CircleAlert,
  success: CircleCheck,
  info: Info,
};

export type IconName = keyof typeof ICONS;

interface IconProps extends Omit<LucideProps, 'size' | 'color'> {
  name: IconName;
  size?: number;
  color?: string;
  strokeWidth?: number;
  fill?: string;
}

export default function Icon({
  name,
  size = 22,
  color = '#1A1A1A',
  strokeWidth = 2,
  fill = 'none',
  ...rest
}: IconProps) {
  const Cmp = ICONS[name] || Package;
  return (
    <Cmp
      size={size}
      color={color}
      strokeWidth={strokeWidth}
      fill={fill}
      {...rest}
    />
  );
}
