# Add project specific ProGuard rules here.
# By default, the flags in this file are appended to flags specified
# in /usr/local/Cellar/android-sdk/24.3.3/tools/proguard/proguard-android.txt
# You can edit the include path and order by changing the proguardFiles
# directive in build.gradle.
#
# For more details, see
#   http://developer.android.com/guide/developing/tools/proguard.html

# Add any project specific keep options here:

# --- Missing class warnings (auto-generated by R8) ---
-dontwarn com.facebook.imagepipeline.cache.AnimatedCache
-dontwarn com.facebook.imagepipeline.cache.AnimationFrames
-dontwarn com.facebook.imagepipeline.nativecode.WebpTranscoder
-dontwarn com.gemalto.jp2.JP2Decoder

# --- React Native ---
-keep class com.facebook.react.** { *; }
-keep class com.facebook.hermes.** { *; }
-keep class com.facebook.jni.** { *; }

# --- Fresco (image loading) ---
-keep class com.facebook.fresco.** { *; }
-keep class com.facebook.imagepipeline.** { *; }
-dontwarn com.facebook.fresco.**
-dontwarn com.facebook.imagepipeline.**

# --- Firebase ---
-keep class com.google.firebase.** { *; }
-dontwarn com.google.firebase.**

# --- Razorpay ---
-keepattributes *Annotation*
-dontwarn com.razorpay.**
-keep class com.razorpay.** { *; }

# --- PDFBox ---
-dontwarn com.tom_roush.pdfbox.**

# --- General ---
-keepattributes SourceFile,LineNumberTable
-keep public class * extends java.lang.Exception
