import mongoose, { Document, Schema } from 'mongoose';

export interface ICustomerUser extends Document {
  phoneNumber?: string;
  email?: string;
  name?: string;
  avatarUrl: string;
  phoneVerified: boolean;
  phoneVerifiedAt: Date | null;
  onboardingCompleted: boolean;
  onboardingCompletedAt: Date | null;
  acceptedTermsVersion: string | null;
  acceptedTermsAt: Date | null;
  acceptedPrivacyVersion: string | null;
  acceptedPrivacyAt: Date | null;
  /** bcrypt hash only — the plaintext auto-generated password is returned once on signup and never persisted. */
  passwordHash: string | null;
  isPasswordAutoGenerated: boolean;
  passwordLastChangedAt: Date | null;
  passwordLastChangedBy: 'system' | 'user' | 'admin' | null;
  meta: Record<string, unknown>;
  lastLogin: Date | null;
  loginCount: number;
  status: 'active' | 'inactive' | 'blocked';
  savedCheckoutContact?: { fullName?: string; email?: string; phone?: string };
  notificationPreferences: {
    push: boolean;
    inApp: boolean;
    sms: boolean;
    whatsapp: boolean;
    email: boolean;
    dnd: boolean;
    dndStartHour: number;
    dndEndHour: number;
    categories?: Record<string, unknown>;
  };
  createdAt: Date;
  updatedAt: Date;
}

const customerUserSchema = new Schema<ICustomerUser>(
  {
    phoneNumber: { type: String },
    email: { type: String, default: undefined },
    name: { type: String },
    avatarUrl: { type: String, default: '' },
    phoneVerified: { type: Boolean, default: false },
    phoneVerifiedAt: { type: Date, default: null },
    onboardingCompleted: { type: Boolean, default: false },
    onboardingCompletedAt: { type: Date, default: null },
    acceptedTermsVersion: { type: String, default: null },
    acceptedTermsAt: { type: Date, default: null },
    acceptedPrivacyVersion: { type: String, default: null },
    acceptedPrivacyAt: { type: Date, default: null },
    passwordHash: { type: String, default: null },
    isPasswordAutoGenerated: { type: Boolean, default: false },
    passwordLastChangedAt: { type: Date, default: null },
    passwordLastChangedBy: { type: String, enum: ['system', 'user', 'admin', null], default: null },
    meta: { type: Schema.Types.Mixed, default: {} },
    lastLogin: { type: Date, default: null },
    loginCount: { type: Number, default: 0 },
    status: { type: String, enum: ['active', 'inactive', 'blocked'], default: 'active' },
    savedCheckoutContact: {
      fullName: { type: String, default: undefined },
      email: { type: String, default: undefined },
      phone: { type: String, default: undefined },
    },
    notificationPreferences: {
      push: { type: Boolean, default: true },
      inApp: { type: Boolean, default: true },
      sms: { type: Boolean, default: true },
      whatsapp: { type: Boolean, default: true },
      email: { type: Boolean, default: true },
      dnd: { type: Boolean, default: false },
      dndStartHour: { type: Number, default: 22 },
      dndEndHour: { type: Number, default: 7 },
      categories: { type: Schema.Types.Mixed, default: undefined },
    },
  },
  { timestamps: true },
);

customerUserSchema.index({ onboardingCompleted: 1 });
customerUserSchema.index({ phoneNumber: 1 }, { sparse: true });
customerUserSchema.index({ email: 1 }, { unique: true, sparse: true, name: 'email_unique_sparse' });
customerUserSchema.index({ status: 1 });

export const CustomerUser =
  (mongoose.models.CustomerUser as mongoose.Model<ICustomerUser>) ||
  mongoose.model<ICustomerUser>('CustomerUser', customerUserSchema, 'customer_users');

export interface IOtpSession extends Document {
  sessionId: string;
  phoneNumber: string | null;
  email: string | null;
  otpHash: string;
  channel: string;
  provider?: string;
  providerResponseId?: string;
  otpSentAt: Date;
  otpExpiresAt: Date;
  resendCount: number;
  attemptCount: number;
  verified: boolean;
  verifiedAt: Date | null;
  purpose: 'login' | 'link_phone' | 'delete_account';
  /** Whether this session was started for an existing-user login or a new-user signup. */
  intent: 'login' | 'signup';
  userId: string | null;
  metadata?: { ip?: string; userAgent?: string; deviceId?: string };
  createdAt: Date;
  updatedAt: Date;
}

const otpSessionSchema = new Schema<IOtpSession>(
  {
    sessionId: { type: String, required: true, unique: true, index: true },
    phoneNumber: { type: String, index: true, default: null },
    email: { type: String, index: true, default: null },
    otpHash: { type: String, required: true },
    channel: { type: String, default: 'sms' },
    provider: { type: String },
    providerResponseId: { type: String },
    otpSentAt: { type: Date, default: Date.now },
    otpExpiresAt: { type: Date, required: true },
    resendCount: { type: Number, default: 0 },
    attemptCount: { type: Number, default: 0 },
    verified: { type: Boolean, default: false },
    verifiedAt: { type: Date, default: null },
    purpose: { type: String, enum: ['login', 'link_phone', 'delete_account'], default: 'login', index: true },
    intent: { type: String, enum: ['login', 'signup'], default: 'login' },
    userId: { type: String, default: null, index: true },
    metadata: { ip: String, userAgent: String, deviceId: String },
  },
  { timestamps: true },
);

otpSessionSchema.index({ otpExpiresAt: 1 }, { expireAfterSeconds: 0 });

export const OtpSession =
  (mongoose.models.CustomerOtpSession as mongoose.Model<IOtpSession>) ||
  mongoose.model<IOtpSession>('CustomerOtpSession', otpSessionSchema, 'customer_otp_sessions');
