import bcrypt from 'bcryptjs';
import { AppError } from '../../utils/AppError';
import { cacheService } from '../../utils/cache';
import { logger } from '../../utils/logger';
import { isPlaceholderCustomerEmail, sanitizeCustomerEmail } from '../../utils/customerDisplay';
import { uploadCustomerAvatarImage } from '../../services/s3.service';
import { isPhoneLocked, normalizePhone } from '../auth/auth.service';
import * as userRepo from './user.repository';
import type { UpdateProfileInput, ChangePasswordInput } from './user.validation';

/** Credential material that must never leave the server on a profile response. */
const PROFILE_SECRET_FIELDS = [
  'passwordHash',
  'password',
  'autoGeneratedPassword',
  'isPasswordAutoGenerated',
  'passwordResetToken',
  'passwordResetExpires',
] as const;

function toPublicProfile<T extends { email?: string | null }>(user: T | null): (T & { email: string | null }) | null {
  if (!user) return null;
  const safe = { ...user, email: sanitizeCustomerEmail(user.email) || null };
  for (const field of PROFILE_SECRET_FIELDS) {
    delete (safe as Record<string, unknown>)[field];
  }
  return safe;
}

async function invalidateCustomerProfileCache() {
  try {
    await cacheService.delPattern('cache:*/user/profile*');
  } catch (err) {
    logger.warn('profile cache invalidation failed', { error: (err as Error).message });
  }
}

export async function getProfile(customerId: string) {
  const user = await userRepo.findProfileById(customerId);
  if (!user) throw AppError.notFound('User');
  return toPublicProfile(user);
}

const PROFILE_ALLOWED_FIELDS = ['name', 'email', 'avatarUrl'] as const;

export async function updateProfile(customerId: string, body: UpdateProfileInput) {
  const updates: Record<string, unknown> = {};
  for (const key of PROFILE_ALLOWED_FIELDS) {
    if (body[key] !== undefined) updates[key] = body[key];
  }
  // Backward-compatible alias from older/mobile payloads.
  if (body.profileImageUrl !== undefined && updates.avatarUrl === undefined) {
    updates.avatarUrl = body.profileImageUrl;
  }

  // Auth phone is immutable via profile update. Linking requires the OTP verify endpoints.
  const phoneAttempt = body.phoneNumber !== undefined || body.mobileNumber !== undefined || body.phone !== undefined;
  if (phoneAttempt) {
    const current = await userRepo.findPhoneStateById(customerId);
    if (isPhoneLocked(current)) {
      throw new AppError('Verified phone number cannot be changed. Contact support for account recovery.', 403, 'PHONE_LOCKED');
    }
    const attempted = normalizePhone((body.phoneNumber ?? body.mobileNumber ?? body.phone) as string);
    const existing = normalizePhone(current?.phoneNumber || '');
    if (attempted && attempted !== existing) {
      throw new AppError('Phone number must be verified via OTP before it can be saved', 403, 'PHONE_OTP_REQUIRED');
    }
  }

  if (updates.avatarUrl !== undefined) {
    updates.avatarUrl = String(updates.avatarUrl || '').trim();
  }

  if (updates.email !== undefined) {
    const normalizedEmail = String(updates.email || '').trim().toLowerCase();
    // Clear placeholder/empty values instead of persisting fakes.
    updates.email = !normalizedEmail || isPlaceholderCustomerEmail(normalizedEmail) ? null : normalizedEmail;
  }

  if (updates.name !== undefined) {
    const normalizedName = String(updates.name || '').trim();
    if (normalizedName.length < 2) throw AppError.badRequest('Full name must be at least 2 characters');
    if (normalizedName.length > 100) throw AppError.badRequest('Full name must be 100 characters or fewer');
    updates.name = normalizedName;
  }

  if (body.savedCheckoutContact !== undefined) {
    const sc = body.savedCheckoutContact;
    if (sc !== null && typeof sc === 'object') {
      const existing = await userRepo.findCheckoutContactById(customerId);
      const prev = existing?.savedCheckoutContact || {};
      const next: Record<string, unknown> = { ...prev };
      if (sc.fullName !== undefined) next.fullName = String(sc.fullName || '').trim().slice(0, 200) || undefined;
      if (sc.email !== undefined) next.email = String(sc.email || '').trim().slice(0, 254) || undefined;
      if (sc.phone !== undefined) next.phone = String(sc.phone || '').replace(/\s/g, '').slice(0, 20) || undefined;
      updates.savedCheckoutContact = next;
    }
  }

  const unsetFields: Record<string, 1> = {};
  if (updates.email === null) {
    delete updates.email;
    unsetFields.email = 1;
  }

  const ops: userRepo.ProfileUpdateOps = {};
  if (Object.keys(updates).length > 0) ops.$set = updates;
  if (Object.keys(unsetFields).length > 0) ops.$unset = unsetFields;

  if (Object.keys(ops).length === 0) {
    const current = await userRepo.findProfileById(customerId);
    if (!current) throw AppError.notFound('User');
    return toPublicProfile(current);
  }

  try {
    const user = await userRepo.updateProfile(customerId, ops);
    if (!user) throw AppError.notFound('User');
    await invalidateCustomerProfileCache();
    return toPublicProfile(user);
  } catch (err) {
    const mongoErr = err as { code?: number; keyPattern?: Record<string, unknown> };
    if (mongoErr?.code === 11000 && mongoErr?.keyPattern?.email) {
      throw AppError.conflict('That email address is already in use');
    }
    throw err;
  }
}

export async function changePassword(customerId: string, input: ChangePasswordInput) {
  const user = await userRepo.findById(customerId);
  if (!user) throw AppError.notFound('User');

  if (user.passwordHash) {
    if (!input.currentPassword) throw AppError.badRequest('Current password is required');
    const match = await bcrypt.compare(input.currentPassword, user.passwordHash);
    if (!match) throw AppError.badRequest('Current password is incorrect');
  }

  user.passwordHash = await bcrypt.hash(input.newPassword, 10);
  user.isPasswordAutoGenerated = false;
  user.passwordLastChangedAt = new Date();
  user.passwordLastChangedBy = 'user';
  await user.save();
}

export async function uploadAvatar(customerId: string, image: string) {
  const avatarUrl = await uploadCustomerAvatarImage(customerId, image);
  const user = await userRepo.updateProfile(customerId, { $set: { avatarUrl } });
  if (!user) throw AppError.notFound('User');
  await invalidateCustomerProfileCache();
  return toPublicProfile(user);
}
